// ---- Games ----
const gameName=t=>({ttt:'Tres en raya',rps:'Piedra, papel o tijera',c4:'Conecta 4'})[t]||'Juego';
const gameEmoji=t=>({ttt:'❌⭕',rps:'✊✋✌️',c4:'🔴🟡'})[t]||'🎮';
function newGame(type,peer,matchId,host,guest){const g={v:1,type,peer,matchId,host,guest,status:'invited',round:1,seq:0,updatedBy:host,scores:{[host]:0,[guest]:0},createdAt:now(),updatedAt:now(),winner:null,draw:false,over:false};if(type==='ttt'){g.board=Array(9).fill('');g.turn=host}else if(type==='c4'){g.board=Array(42).fill('');g.turn=host;g.winCells=[]}else{g.choices={[host]:null,[guest]:null};g.resolved=false}return g}
function clone(o){return JSON.parse(JSON.stringify(o))}
function saveGame(peer,g){games.set(peer,clone(g));saveGames();if(currentPeer===peer&&!$('gameOverlay').hidden)renderGame(g)}
function newerState(a,b){if(!b)return true;if(a.matchId!==b.matchId)return (a.createdAt||0)>(b.createdAt||0);if((a.round||0)!==(b.round||0))return (a.round||0)>(b.round||0);if((a.seq||0)!==(b.seq||0))return (a.seq||0)>(b.seq||0);return String(a.updatedBy||'')>String(b.updatedBy||'')}
async function sendGame(peer,packet){try{return await queueSecure(peer,{type:'game',packet,ts:now()})}catch(e){toast('No pude enviar la jugada',true);return null}}
function handleGamePacket(peer,p){if(!p||!p.op)return;let g=games.get(peer);
  if(p.op==='invite'&&p.state){const s=p.state;if(s.guest!==identity.id||s.host!==peer)return;pendingInvites.set(peer,{ts:now(),state:s});saveGames();if(currentPeer===peer)showInvite(peer,pendingInvites.get(peer));else toast(`${peerName(peer)} te invitó a ${gameName(s.type)} 🎮`);return}
  if(p.op==='decline'){if(g&&g.matchId===p.matchId){g.status='declined';g.updatedAt=now();saveGame(peer,g)}pendingInvites.delete(peer);saveGames();if(currentPeer===peer)renderGame(g);return}
  if(p.op==='sync-request'){if(g&&g.matchId===p.matchId)sendGame(peer,{op:'state',state:clone(g)});return}
  if(p.op==='state'&&p.state){const s=p.state;if(s.peer!==identity.id&&s.peer!==peer)s.peer=peer;if(![s.host,s.guest].includes(identity.id)||![s.host,s.guest].includes(peer))return;if(newerState(s,g)){s.peer=peer;pendingInvites.delete(peer);saveGame(peer,s)}return}
  if(p.op==='rps-choice'){if(!g||g.matchId!==p.matchId||g.type!=='rps'||g.status!=='active'||p.round!==g.round||![g.host,g.guest].includes(p.actor)||!['rock','paper','scissors'].includes(p.choice))return;if(!g.choices)g.choices={[g.host]:null,[g.guest]:null};if(!g.choices[p.actor]){g.choices[p.actor]=p.choice;g.seq++;g.updatedBy=p.actor;g.updatedAt=now();resolveRps(g);saveGame(peer,g);if(g.resolved)sendGame(peer,{op:'state',state:clone(g)})}return}
}
function showGamePicker(){if(!currentPeer)return;const g=games.get(currentPeer),inv=pendingInvites.get(currentPeer);$('gameCard').innerHTML=`<div class="game-top"><h2>🎮 Juegos con ${esc(peerName(currentPeer))}</h2><button class="game-close" id="gc">×</button></div><p class="game-sub">Elige un juego para invitar a esta persona.</p>${inv?`<button class="game-action" id="viewInvite">📨 Ver invitación</button>`:''}${g&&['active','invited'].includes(g.status)?`<button class="game-action ghost" id="resumeGame">▶ Continuar partida</button>`:''}<div class="game-grid" style="margin-top:12px"><button class="game-choice" data-game="ttt"><span>❌⭕</span><b>Tres en raya</b><small>Por turnos</small></button><button class="game-choice" data-game="rps"><span>✊✋✌️</span><b>Piedra, papel o tijera</b><small>Elección simultánea</small></button><button class="game-choice" data-game="c4"><span>🔴🟡</span><b>Conecta 4</b><small>Por turnos</small></button></div>`;$('gameOverlay').hidden=false;$('gc').onclick=closeGame;document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>inviteGame(b.dataset.game));if($('viewInvite'))$('viewInvite').onclick=()=>showInvite(currentPeer,inv);if($('resumeGame'))$('resumeGame').onclick=()=>renderGame(g)}
async function inviteGame(type){const peer=currentPeer,matchId=randomId(),g=newGame(type,peer,matchId,identity.id,peer);g.status='invited';saveGame(peer,g);renderGame(g);await sendGame(peer,{op:'invite',state:clone(g)})}
function showInvite(peer,inv){if(!inv?.state||currentPeer!==peer)return;const s=inv.state;$('gameCard').innerHTML=`<div class="game-top"><h2>${gameEmoji(s.type)} Invitación</h2><button class="game-close" id="gc">×</button></div><p class="game-sub"><b>${esc(peerName(peer))}</b> quiere jugar <b>${esc(gameName(s.type))}</b> contigo.</p><div class="game-actions"><button class="game-action" id="acceptGame">Aceptar</button><button class="game-action ghost" id="declineGame">Ahora no</button></div>`;$('gameOverlay').hidden=false;$('gc').onclick=closeGame;$('acceptGame').onclick=()=>acceptGame(peer,inv);$('declineGame').onclick=()=>declineGame(peer,inv)}
async function acceptGame(peer,inv){const g=clone(inv.state);g.peer=peer;g.status='active';g.seq++;g.updatedBy=identity.id;g.updatedAt=now();pendingInvites.delete(peer);saveGame(peer,g);renderGame(g);await sendGame(peer,{op:'state',state:clone(g)})}
async function declineGame(peer,inv){pendingInvites.delete(peer);saveGames();closeGame();await sendGame(peer,{op:'decline',matchId:inv.state.matchId})}
function closeGame(){$('gameOverlay').hidden=true}
function score(g,id){return Number(g?.scores?.[id]||0)}
function renderGame(g){if(!g)return showGamePicker();let body='';if(g.status==='invited')body=`<div class="game-status">Esperando a que ${esc(peerName(g.peer))} acepte…</div>`;else if(g.status==='declined')body='<div class="game-status">Invitación rechazada.</div>';else if(g.type==='ttt')body=renderTtt(g);else if(g.type==='c4')body=renderC4(g);else body=renderRps(g);$('gameCard').innerHTML=`<div class="game-top"><h2>${gameEmoji(g.type)} ${esc(gameName(g.type))}</h2><button class="game-close" id="gc">×</button></div><div class="score"><span>Tú: <b>${score(g,identity.id)}</b></span><span>${esc(peerName(g.peer))}: <b>${score(g,g.peer)}</b></span><span>Ronda ${g.round}</span></div>${body}<div class="game-actions"><button class="game-action ghost" id="syncGame">↻ Sincronizar</button><button class="game-action ghost" id="changeGame">Cambiar juego</button></div>`;$('gameOverlay').hidden=false;$('gc').onclick=closeGame;$('syncGame').onclick=()=>sendGame(g.peer,{op:'sync-request',matchId:g.matchId});$('changeGame').onclick=showGamePicker;bindGame(g)}
function statusText(g){if(g.over){if(g.draw)return'Empate';return g.winner===identity.id?'¡Ganaste! 🎉':`${peerName(g.peer)} ganó esta ronda`}if(g.type==='rps'){const mine=g.choices?.[identity.id],theirs=g.choices?.[g.peer];if(mine&&!theirs)return'Esperando la jugada del otro…';return'Elige tu jugada'}return g.turn===identity.id?'Tu turno':`Turno de ${peerName(g.peer)}`}
function renderTtt(g){return `<div class="game-status">${esc(statusText(g))}</div><div class="ttt">${g.board.map((v,i)=>`<button data-cell="${i}" ${g.status!=='active'||g.over||g.turn!==identity.id||v?'disabled':''}>${v==='X'?'❌':v==='O'?'⭕':''}</button>`).join('')}</div>${g.over?'<div class="game-actions"><button class="game-action" id="nextRound">Otra ronda</button></div>':''}`}
function renderC4(g){return `<div class="game-status">${esc(statusText(g))}</div><div class="c4">${g.board.map((v,i)=>`<button data-col="${i%7}" class="${v==='R'?'red':v==='Y'?'yellow':''} ${g.winCells?.includes(i)?'win':''}" ${g.status!=='active'||g.over||g.turn!==identity.id?'disabled':''}></button>`).join('')}</div>${g.over?'<div class="game-actions"><button class="game-action" id="nextRound">Otra ronda</button></div>':''}`}
function rpsEmoji(x){return x==='rock'?'✊':x==='paper'?'✋':x==='scissors'?'✌️':'❔'}
function renderRps(g){const mine=g.choices?.[identity.id],theirs=g.choices?.[g.peer];const opts=[['rock','✊'],['paper','✋'],['scissors','✌️']].map(([k,e])=>`<button data-rps="${k}" class="${mine===k?'sel':''}" ${g.status!=='active'||mine||g.resolved?'disabled':''}>${e}</button>`).join('');const reveal=g.resolved?`<div class="reveal"><span>${rpsEmoji(mine)}</span><b>VS</b><span>${rpsEmoji(theirs)}</span></div>`:'';return `<div class="game-status">${esc(statusText(g))}</div><div class="rps">${opts}</div>${reveal}${g.resolved?'<div class="game-actions"><button class="game-action" id="nextRound">Otra ronda</button></div>':''}`}
function bindGame(g){document.querySelectorAll('[data-cell]').forEach(b=>b.onclick=()=>tttMove(g,Number(b.dataset.cell)));document.querySelectorAll('[data-col]').forEach(b=>b.onclick=()=>c4Move(g,Number(b.dataset.col)));document.querySelectorAll('[data-rps]').forEach(b=>b.onclick=()=>rpsMove(g,b.dataset.rps));if($('nextRound'))$('nextRound').onclick=()=>nextRound(g)}
function mark(g,id){if(g.type==='ttt')return id===g.host?'X':'O';return id===g.host?'R':'Y'}
function checkTtt(b){for(const w of [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]])if(b[w[0]]&&b[w[0]]===b[w[1]]&&b[w[1]]===b[w[2]])return w;return null}
async function tttMove(g,cell){if(g.status!=='active'||g.over||g.turn!==identity.id||g.board[cell])return;g.board[cell]=mark(g,identity.id);const win=checkTtt(g.board);if(win){g.over=true;g.winner=identity.id;g.scores[identity.id]=(g.scores[identity.id]||0)+1}else if(g.board.every(Boolean)){g.over=true;g.draw=true}else g.turn=g.peer;g.seq++;g.updatedBy=identity.id;g.updatedAt=now();saveGame(g.peer,g);await sendGame(g.peer,{op:'state',state:clone(g)})}
function checkC4(b){for(let r=0;r<6;r++)for(let c=0;c<7;c++){const v=b[r*7+c];if(!v)continue;for(const[dc,dr]of [[1,0],[0,1],[1,1],[1,-1]]){const cells=[];let ok=true;for(let k=0;k<4;k++){const cc=c+dc*k,rr=r+dr*k;if(cc<0||cc>=7||rr<0||rr>=6||b[rr*7+cc]!==v){ok=false;break}cells.push(rr*7+cc)}if(ok)return cells}}return null}
async function c4Move(g,col){if(g.status!=='active'||g.over||g.turn!==identity.id)return;let row=-1;for(let r=5;r>=0;r--)if(!g.board[r*7+col]){row=r;break}if(row<0)return;g.board[row*7+col]=mark(g,identity.id);const win=checkC4(g.board);if(win){g.over=true;g.winner=identity.id;g.winCells=win;g.scores[identity.id]=(g.scores[identity.id]||0)+1}else if(g.board.every(Boolean)){g.over=true;g.draw=true}else g.turn=g.peer;g.seq++;g.updatedBy=identity.id;g.updatedAt=now();saveGame(g.peer,g);await sendGame(g.peer,{op:'state',state:clone(g)})}
function rpsWinner(a,b){if(a===b)return null;if((a==='rock'&&b==='scissors')||(a==='paper'&&b==='rock')||(a==='scissors'&&b==='paper'))return'first';return'second'}
function resolveRps(g){if(g.resolved)return;const a=g.choices?.[g.host],b=g.choices?.[g.guest];if(!a||!b)return;const w=rpsWinner(a,b);g.resolved=true;g.over=true;g.draw=!w;g.winner=w==='first'?g.host:w==='second'?g.guest:null;if(g.winner)g.scores[g.winner]=(g.scores[g.winner]||0)+1}
async function rpsMove(g,choice){if(g.status!=='active'||g.resolved||g.choices?.[identity.id])return;g.choices[identity.id]=choice;g.seq++;g.updatedBy=identity.id;g.updatedAt=now();resolveRps(g);saveGame(g.peer,g);await sendGame(g.peer,{op:'rps-choice',matchId:g.matchId,round:g.round,actor:identity.id,choice});if(g.resolved)await sendGame(g.peer,{op:'state',state:clone(g)})}
function resetRound(g,n){g.round=n;g.over=false;g.winner=null;g.draw=false;g.updatedAt=now();g.updatedBy=identity.id;g.seq++;if(g.type==='ttt'){g.board=Array(9).fill('');g.turn=n%2?g.host:g.guest}else if(g.type==='c4'){g.board=Array(42).fill('');g.turn=n%2?g.host:g.guest;g.winCells=[]}else{g.choices={[g.host]:null,[g.guest]:null};g.resolved=false}}
async function nextRound(g){resetRound(g,g.round+1);saveGame(g.peer,g);await sendGame(g.peer,{op:'state',state:clone(g)})}

