(()=>{
const RELAYS=['wss://relay.damus.io','wss://nos.lol','wss://relay.snort.social','wss://relay.primal.net'];
const APP_TAG='dupi-chat-html-v2',PROFILE_KIND=30078,GIFT_WRAP_KIND=1059,GAME_PREFIX='__DUPI_GAME_V2__:';
const $=id=>document.getElementById(id),mem={};
let N,pool,sk=null,pk=null,username='',currentPeer=null,contacts=new Map(),messages=new Map(),seen=new Set(),profileSub,dmSub,presenceTimer,filterMode='all',activeGame=null,pendingInvite=null;
function loadLib(){if(window.NostrTools)return start();let i=0,urls=['https://unpkg.com/nostr-tools@2.23.5/lib/nostr.bundle.js','https://cdn.jsdelivr.net/npm/nostr-tools@2.23.5/lib/nostr.bundle.js'];const next=()=>{if(i>=urls.length){$('bootText').textContent='No pude cargar la red de mensajería. Revisa Internet y recarga.';return}let s=document.createElement('script'),done=false,t=setTimeout(()=>{if(!done){done=true;s.remove();next()}},7000);s.src=urls[i++];s.onload=()=>{if(done)return;done=true;clearTimeout(t);window.NostrTools?start():next()};s.onerror=()=>{if(done)return;done=true;clearTimeout(t);next()};document.head.appendChild(s)};next()}
function start(){if(window.__dupiStarted)return;window.__dupiStarted=true;N=window.NostrTools;if(!N?.SimplePool||!N?.nip17){$('bootText').textContent='El motor cargó incompleto. Recarga la página.';return}pool=new N.SimplePool();if(!Promise.any)Promise.any=ps=>new Promise((res,rej)=>{let e=[],n=0;for(const p of ps){n++;Promise.resolve(p).then(res,x=>{e.push(x);if(!--n)rej(e)})}});bindUI();if(loadLocal())startApp();else $('registerModal').hidden=false;$('bootNote').classList.add('ok')}
function get(k){try{return localStorage.getItem(k)}catch{return mem[k]||null}}function set(k,v){try{localStorage.setItem(k,v)}catch{mem[k]=v}}function del(k){try{localStorage.removeItem(k)}catch{delete mem[k]}}
function hex(a){return Array.from(a,b=>b.toString(16).padStart(2,'0')).join('')}function fromHex(s){if(!/^[0-9a-f]{64}$/i.test(s))throw 0;return new Uint8Array(s.match(/.{2}/g).map(x=>parseInt(x,16)))}
const now=()=>Math.floor(Date.now()/1000),short=x=>x?x.slice(0,6):'------',json=s=>{try{return JSON.parse(s)}catch{return null}},initials=n=>(n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase();
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(text,bad=false){let d=document.createElement('div');d.className='toast'+(bad?' bad':'');d.textContent=text;$('toasts').appendChild(d);setTimeout(()=>d.remove(),3300)}
function net(cls,text){$('netState').className='net '+cls;$('netState').querySelector('span').textContent=text}
function fmtTime(ts){return new Date(ts*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}function fmtDay(ts){let d=new Date(ts*1000),t=new Date();if(d.toDateString()===t.toDateString())return'HOY';let y=new Date();y.setDate(y.getDate()-1);return d.toDateString()===y.toDateString()?'AYER':d.toLocaleDateString()}
function peerName(peer){return contacts.get(peer)?.username||'Usuario '+short(peer)}function online(c){return!!c.lastSeen&&now()-c.lastSeen<130}
function saveLocal(){set('dupi_chat_identity',JSON.stringify({sk:hex(sk),username}))}function loadLocal(){let x=json(get('dupi_chat_identity')||'');if(!x?.sk||!x?.username)return false;try{sk=fromHex(x.sk);pk=N.getPublicKey(sk);username=x.username;return true}catch{return false}}
async function publish(ev){try{await Promise.any(pool.publish(RELAYS,ev));net('ok','Conectado');return true}catch{net('bad','Sin conexión');return false}}
async function publishProfile(){if(!sk)return;let ev=N.finalizeEvent({kind:PROFILE_KIND,created_at:now(),tags:[['d','profile'],['t',APP_TAG]],content:JSON.stringify({username,lastSeen:now(),app:APP_TAG})},sk);await publish(ev);ingestProfile(ev)}
function ingestProfile(ev){if(ev.kind!==PROFILE_KIND||!ev.tags.some(t=>t[0]==='t'&&t[1]===APP_TAG))return;let d=json(ev.content);if(!d?.username)return;let old=contacts.get(ev.pubkey);if(old&&old.eventTime>ev.created_at)return;contacts.set(ev.pubkey,{pubkey:ev.pubkey,username:String(d.username).slice(0,24),lastSeen:+(d.lastSeen||ev.created_at),eventTime:ev.created_at});renderContacts();if(currentPeer===ev.pubkey)renderChatHeader()}
async function refreshProfiles(){if(!sk)return;$('refreshBtn').disabled=true;try{let evs=await pool.querySync(RELAYS,{kinds:[PROFILE_KIND],'#t':[APP_TAG],limit:500});evs.forEach(ingestProfile);net('ok','Conectado')}catch{net('bad','No pude actualizar')}$('refreshBtn').disabled=false}
function subscribeProfiles(){try{profileSub?.close?.()}catch{}profileSub=pool.subscribe(RELAYS,{kinds:[PROFILE_KIND],'#t':[APP_TAG],since:now()-2592000},{onevent:ingestProfile})}
function peerFromRumor(r){if(r.pubkey===pk){let p=r.tags.find(t=>t[0]==='p'&&t[1]!==pk);return p?.[1]||null}return r.pubkey}
async function ingestWrap(ev){if(seen.has(ev.id))return;seen.add(ev.id);try{let r=N.nip17.unwrapEvent(ev,sk);if(r.kind!==14)return;let peer=peerFromRumor(r);if(!peer||peer===pk)return;if(r.content.startsWith(GAME_PREFIX)){if(r.pubkey!==pk){let p=json(r.content.slice(GAME_PREFIX.length));if(p)handleGamePacket(p,peer)}return}let a=messages.get(peer)||[];if(a.some(m=>m.id===r.id))return;a.push({id:r.id,sender:r.pubkey,text:r.content,created_at:r.created_at});a.sort((a,b)=>a.created_at-b.created_at);messages.set(peer,a);if(!contacts.has(peer))contacts.set(peer,{pubkey:peer,username:'Usuario '+short(peer),lastSeen:0,eventTime:0});renderContacts();if(currentPeer===peer)renderMessages()}catch{}}
function subscribeDMs(){try{dmSub?.close?.()}catch{}dmSub=pool.subscribe(RELAYS,{kinds:[GIFT_WRAP_KIND],'#p':[pk],since:now()-2592000},{onevent:ingestWrap})}
async function loadHistory(){try{let evs=await pool.querySync(RELAYS,{kinds:[GIFT_WRAP_KIND],'#p':[pk],limit:1000});evs.sort((a,b)=>a.created_at-b.created_at);for(const e of evs)await ingestWrap(e)}catch{}}
async function sendPrivate(peer,text){try{let wraps=N.nip17.wrapManyEvents(sk,[{publicKey:peer}],text),ok=[];for(const w of wraps)ok.push(await publish(w));return!!ok[1]}catch{return false}}
async function sendMessage(){let text=$('messageInput').value.trim();if(!text||!currentPeer)return;if(text.length>4000)return toast('Mensaje demasiado largo',true);$('sendBtn').disabled=true;let peer=currentPeer;try{let wraps=N.nip17.wrapManyEvents(sk,[{publicKey:peer}],text),local=N.nip17.unwrapEvent(wraps[0],sk),ok=[];for(const w of wraps)ok.push(await publish(w));if(!ok[1])throw 0;let a=messages.get(peer)||[];if(!a.some(m=>m.id===local.id))a.push({id:local.id,sender:pk,text,created_at:local.created_at});messages.set(peer,a);$('messageInput').value='';resize();renderMessages();renderContacts()}catch{toast('No pude enviar. Revisa Internet.',true)}$('sendBtn').disabled=false}
function latest(peer){let a=messages.get(peer)||[];return a[a.length-1]||null}
function renderContacts(){let q=$('search').value.trim().toLowerCase(),list=[...contacts.values()].filter(c=>c.pubkey!==pk);if(filterMode==='online')list=list.filter(online);if(q)list=list.filter(c=>c.username.toLowerCase().includes(q)||c.pubkey.includes(q));list.sort((a,b)=>(latest(b.pubkey)?.created_at||0)-(latest(a.pubkey)?.created_at||0)||(b.lastSeen||0)-(a.lastSeen||0));$('contactList').innerHTML='';if(!list.length){$('contactList').innerHTML='<div class="empty-list"><strong>No hay usuarios todavía</strong>Comparte el enlace y toca ↻ cuando la otra persona entre.</div>';return}for(const c of list){let m=latest(c.pubkey),el=document.createElement('div');el.className='contact'+(currentPeer===c.pubkey?' active':'');el.innerHTML=`<div class="avatar">${esc(initials(c.username))}</div><div class="contact-main"><div class="row1"><b>${esc(c.username)}</b><time>${m?fmtTime(m.created_at):''}</time></div><div class="row2"><span class="preview">${m?esc((m.sender===pk?'Tú: ':'')+m.text):'@'+short(c.pubkey)}</span><span><i class="online-dot ${online(c)?'on':''}"></i>${online(c)?'online':''}</span></div></div>`;el.onclick=()=>openChat(c.pubkey);$('contactList').appendChild(el)}}
function openChat(peer){currentPeer=peer;$('welcome').hidden=true;$('chat').classList.add('open');$('messageInput').disabled=false;$('sendBtn').disabled=false;$('gameBtn').disabled=false;renderContacts();renderChatHeader();renderMessages()}
function renderChatHeader(){let c=contacts.get(currentPeer);if(!c)return;$('chatAvatar').textContent=initials(c.username);$('chatName').textContent=c.username;$('chatStatus').textContent=online(c)?'en línea':'@'+short(c.pubkey)}
function renderMessages(){let box=$('messages'),a=messages.get(currentPeer)||[],day='';box.innerHTML='';for(const m of a){let d=fmtDay(m.created_at);if(d!==day){day=d;let s=document.createElement('div');s.className='date-pill';s.textContent=d;box.appendChild(s)}let e=document.createElement('div');e.className='msg '+(m.sender===pk?'mine':'theirs');let tx=document.createElement('span');tx.textContent=m.text;let meta=document.createElement('span');meta.className='meta';meta.innerHTML=fmtTime(m.created_at)+(m.sender===pk?' <span class="ticks">✓✓</span>':'');e.append(tx,meta);box.appendChild(e)}if(!a.length){let s=document.createElement('div');s.className='date-pill';s.textContent='Inicio del chat';box.appendChild(s)}requestAnimationFrame(()=>box.scrollTop=box.scrollHeight)}
function resize(){let t=$('messageInput');t.style.height='42px';t.style.height=Math.min(t.scrollHeight,120)+'px'}
async function register(){let name=$('usernameInput').value.trim().replace(/\s+/g,' ');$('registerErr').textContent='';if(name.length<2)return $('registerErr').textContent='Pon al menos 2 letras.';sk=N.generateSecretKey();pk=N.getPublicKey(sk);username=name.slice(0,24);saveLocal();$('registerModal').hidden=true;await startApp()}
async function startApp(){$('meName').textContent=username;$('meAvatar').textContent=initials(username);net('','Conectando…');contacts.set(pk,{pubkey:pk,username,lastSeen:now(),eventTime:now()});subscribeProfiles();subscribeDMs();await Promise.allSettled([publishProfile(),refreshProfiles(),loadHistory()]);clearInterval(presenceTimer);presenceTimer=setInterval(publishProfile,60000);renderContacts()}
function bindUI(){$('registerBtn').onclick=register;$('usernameInput').onkeydown=e=>{if(e.key==='Enter')register()};$('refreshBtn').onclick=async()=>{await publishProfile();await refreshProfiles();toast('Usuarios actualizados')};$('search').oninput=renderContacts;document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');filterMode=b.dataset.filter;renderContacts()});$('sendBtn').onclick=sendMessage;$('messageInput').oninput=resize;$('messageInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}};$('backBtn').onclick=()=>$('chat').classList.remove('open');$('emojiBtn').onclick=()=>{if(!$('messageInput').disabled){$('messageInput').value+=' 😊';resize()}};$('menuBtn').onclick=e=>{e.stopPropagation();$('menu').hidden=!$('menu').hidden};document.addEventListener('click',()=>$('menu').hidden=true);$('shareBtn').onclick=async()=>{try{navigator.share?await navigator.share({title:'Dupi Chat',text:'Únete a Dupi Chat',url:location.href}):await navigator.clipboard.writeText(location.href)}catch{}};$('copyIdBtn').onclick=async()=>{try{await navigator.clipboard.writeText(pk);toast('ID copiado')}catch{}};$('renameBtn').onclick=()=>{let n=prompt('Nuevo nombre:',username);if(n&&n.trim().length>1){username=n.trim().slice(0,24);saveLocal();$('meName').textContent=username;$('meAvatar').textContent=initials(username);publishProfile()}};$('logoutBtn').onclick=()=>{if(confirm('¿Borrar la identidad de este navegador?')){del('dupi_chat_identity');location.reload()}};$('gameBtn').onclick=showGamePicker;$('gameOverlay').onclick=e=>{if(e.target===$('gameOverlay'))closeGame()};window.addEventListener('online',()=>{net('','Reconectando…');publishProfile();refreshProfiles()});window.addEventListener('offline',()=>net('bad','Sin Internet'));if(window.visualViewport){let f=()=>document.documentElement.style.setProperty('--vvh',visualViewport.height+'px');visualViewport.addEventListener('resize',f);f()}}
const gameName=t=>({ttt:'Tres en raya',rps:'Piedra, papel o tijera',c4:'Conecta 4'})[t]||'Juego',gameEmoji=t=>({ttt:'❌⭕',rps:'✊✋✌️',c4:'🔴🟡'})[t]||'🎮';
function gameId(){let a=new Uint8Array(8);crypto.getRandomValues(a);return hex(a)}function closeGame(){$('gameOverlay').hidden=true}function openGame(){$('gameOverlay').hidden=false}
function emptyGame(type,peer,match,host){if(type==='ttt')return{type,peer,match,host,board:Array(9).fill(''),turn:host,seq:0,over:false,winner:null,scores:{me:0,them:0},round:1};if(type==='c4')return{type,peer,match,host,board:Array(42).fill(''),turn:host,seq:0,over:false,winner:null,winCells:[],scores:{me:0,them:0},round:1};return{type,peer,match,host,seq:0,over:false,myChoice:null,theirChoice:null,scores:{me:0,them:0},round:1}}
async function gameSend(peer,p){return sendPrivate(peer,GAME_PREFIX+JSON.stringify(Object.assign({v:2,ts:now()},p)))}
function showGamePicker(){if(!currentPeer)return toast('Abre un chat primero.',true);let resume=activeGame&&activeGame.peer===currentPeer;$('gameCard').innerHTML=`<div class="game-top"><h2>🎮 Juegos con ${esc(peerName(currentPeer))}</h2><button class="game-close" id="gc">×</button></div><p class="game-sub">Elige un juego y le llegará una invitación privada.</p>${resume?'<button class="game-action" id="resume" style="width:100%;margin-bottom:12px">▶ Continuar partida</button>':''}<div class="game-grid"><button class="game-choice" data-g="ttt"><span class="gi">❌⭕</span><span><b>Tres en raya</b><small>Clásico por turnos</small></span></button><button class="game-choice" data-g="rps"><span class="gi">✊✋✌️</span><span><b>Piedra, papel o tijera</b><small>Una jugada rápida</small></span></button><button class="game-choice" data-g="c4"><span class="gi">🔴🟡</span><span><b>Conecta 4</b><small>Conecta cuatro fichas</small></span></button></div>`;openGame();$('gc').onclick=closeGame;if($('resume'))$('resume').onclick=renderGame;document.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>inviteGame(b.dataset.g))}
async function inviteGame(type){let peer=currentPeer,match=gameId();activeGame=emptyGame(type,peer,match,pk);$('gameCard').innerHTML=`<div class="game-top"><h2>${gameEmoji(type)} ${gameName(type)}</h2><button class="game-close" id="gc">×</button></div><div class="game-status pulse">Invitación enviada a ${esc(peerName(peer))}…</div>`;$('gc').onclick=closeGame;if(!await gameSend(peer,{action:'invite',game:type,match,host:pk})){toast('No pude enviar la invitación.',true);activeGame=null;closeGame()}}
function showInvite(x){pendingInvite=x;$('gameCard').innerHTML=`<div class="game-top"><h2>🎮 Te invitaron a jugar</h2></div><div style="text-align:center;font-size:56px">${gameEmoji(x.game)}</div><p class="game-sub" style="text-align:center"><b>${esc(peerName(x.peer))}</b> quiere jugar <b>${gameName(x.game)}</b>.</p><div class="game-actions" style="justify-content:center"><button class="game-action" id="accept">Aceptar</button><button class="game-action ghost" id="decline">Ahora no</button></div>`;openGame();$('accept').onclick=acceptInvite;$('decline').onclick=declineInvite}
async function acceptInvite(){let x=pendingInvite;if(!x)return;pendingInvite=null;activeGame=emptyGame(x.game,x.peer,x.match,x.host);await gameSend(x.peer,{action:'accept',game:x.game,match:x.match,host:x.host});renderGame()}
async function declineInvite(){let x=pendingInvite;pendingInvite=null;closeGame();if(x)await gameSend(x.peer,{action:'decline',game:x.game,match:x.match})}
function handleGamePacket(p,peer){if(!p||p.v!==2)return;if(p.action==='invite'){if(p.ts&&now()-p.ts>300)return;if(activeGame&&!activeGame.over){gameSend(peer,{action:'decline',game:p.game,match:p.match});return}showInvite({peer,game:p.game,match:p.match,host:p.host||peer});return}if(p.action==='decline'){if(activeGame?.match===p.match){toast(peerName(peer)+' no aceptó la partida.');activeGame=null;closeGame()}return}if(p.action==='accept'){if(activeGame?.match===p.match){toast(peerName(peer)+' aceptó 🎮');renderGame()}return}if(!activeGame||activeGame.match!==p.match||activeGame.peer!==peer)return;if(p.action==='state'&&['ttt','c4'].includes(activeGame.type)){if(typeof p.seq!=='number'||p.seq<=activeGame.seq||!Array.isArray(p.board)||p.board.length!==activeGame.board.length)return;activeGame.board=p.board.slice();activeGame.seq=p.seq;activeGame.turn=p.turn;activeGame.over=!!p.over;activeGame.winner=p.winner||null;activeGame.winCells=p.winCells||[];if(activeGame.over&&activeGame.winner===pk)activeGame.scores.me++;else if(activeGame.over&&activeGame.winner===peer)activeGame.scores.them++;renderGame();return}if(p.action==='rps'&&activeGame.type==='rps'&&p.round===activeGame.round&&['rock','paper','scissors'].includes(p.choice)){activeGame.theirChoice=p.choice;finishRps();renderGame();return}if(p.action==='reset'){resetGame(Math.max(activeGame.round+1,p.round||2));renderGame()}}
function status(){if(activeGame.over){if(activeGame.winner==='draw')return'Empate 🤝';return activeGame.winner===pk?'¡Ganaste! 🏆':peerName(activeGame.peer)+' ganó'}if(activeGame.type==='rps')return activeGame.myChoice?'Esperando al rival…':'Elige tu jugada';return activeGame.turn===pk?'Tu turno 👇':'Turno de '+peerName(activeGame.peer)}
function head(title){return`<div class="game-top"><h2>${title}</h2><button class="game-close" id="gc">×</button></div><div class="scoreline"><span>Tú: <b>${activeGame.scores.me}</b></span><span>${esc(peerName(activeGame.peer))}: <b>${activeGame.scores.them}</b></span></div><div class="game-status">${esc(status())}</div>`}
function common(){$('gc').onclick=closeGame;if($('rematch'))$('rematch').onclick=rematch;if($('quit'))$('quit').onclick=()=>{activeGame=null;closeGame()}}
function renderGame(){if(!activeGame)return showGamePicker();openGame();activeGame.type==='ttt'?renderTTT():activeGame.type==='c4'?renderC4():renderRPS()}
function tWin(b){let L=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];return L.find(l=>b[l[0]]&&b[l[0]]===b[l[1]]&&b[l[0]]===b[l[2]])||null}
function renderTTT(){let h=head('❌⭕ Tres en raya')+'<div class="ttt">';activeGame.board.forEach((v,i)=>h+=`<button data-cell="${i}" ${activeGame.turn!==pk||activeGame.over||v?'disabled':''}>${v}</button>`);h+='</div><div class="game-actions">'+(activeGame.over?'<button class="game-action" id="rematch">Otra ronda</button>':'')+'<button class="game-action ghost" id="quit">Salir</button></div>';$('gameCard').innerHTML=h;common();document.querySelectorAll('[data-cell]').forEach(b=>b.onclick=()=>tttMove(+b.dataset.cell))}
async function tttMove(i){if(activeGame.turn!==pk||activeGame.over||activeGame.board[i])return;activeGame.board[i]=activeGame.host===pk?'X':'O';activeGame.seq++;let w=tWin(activeGame.board);if(w){activeGame.over=true;activeGame.winner=pk;activeGame.scores.me++}else if(activeGame.board.every(Boolean)){activeGame.over=true;activeGame.winner='draw'}else activeGame.turn=activeGame.peer;renderTTT();await sendState()}
function cWin(b){for(let r=0;r<6;r++)for(let c=0;c<7;c++){let v=b[r*7+c];if(!v)continue;for(const[dR,dC]of[[0,1],[1,0],[1,1],[1,-1]]){let x=[];for(let k=0;k<4;k++){let rr=r+dR*k,cc=c+dC*k;if(rr<0||rr>=6||cc<0||cc>=7)break;x.push(rr*7+cc)}if(x.length===4&&x.every(i=>b[i]===v))return x}}return null}
function renderC4(){let h=head('🔴🟡 Conecta 4')+'<div class="c4">';activeGame.board.forEach((v,i)=>h+=`<button data-col="${i%7}" class="${v==='R'?'red':v==='Y'?'yellow':''} ${(activeGame.winCells||[]).includes(i)?'win':''}" ${activeGame.turn!==pk||activeGame.over?'disabled':''}></button>`);h+='</div><div class="game-actions">'+(activeGame.over?'<button class="game-action" id="rematch">Otra ronda</button>':'')+'<button class="game-action ghost" id="quit">Salir</button></div>';$('gameCard').innerHTML=h;common();document.querySelectorAll('[data-col]').forEach(b=>b.onclick=()=>c4Move(+b.dataset.col))}
async function c4Move(col){if(activeGame.turn!==pk||activeGame.over)return;let idx=-1;for(let r=5;r>=0;r--){let i=r*7+col;if(!activeGame.board[i]){idx=i;break}}if(idx<0)return;activeGame.board[idx]=activeGame.host===pk?'R':'Y';activeGame.seq++;let w=cWin(activeGame.board);if(w){activeGame.over=true;activeGame.winner=pk;activeGame.winCells=w;activeGame.scores.me++}else if(activeGame.board.every(Boolean)){activeGame.over=true;activeGame.winner='draw'}else activeGame.turn=activeGame.peer;renderC4();await sendState()}
async function sendState(){await gameSend(activeGame.peer,{action:'state',game:activeGame.type,match:activeGame.match,seq:activeGame.seq,board:activeGame.board,turn:activeGame.turn,over:activeGame.over,winner:activeGame.winner,winCells:activeGame.winCells||[]})}
const rIcon=x=>({rock:'✊',paper:'✋',scissors:'✌️'})[x]||'❔';function rResult(a,b){if(a===b)return 0;if(a==='rock'&&b==='scissors'||a==='paper'&&b==='rock'||a==='scissors'&&b==='paper')return 1;return-1}function finishRps(){if(!activeGame.myChoice||!activeGame.theirChoice||activeGame.over)return;activeGame.over=true;let r=rResult(activeGame.myChoice,activeGame.theirChoice);activeGame.winner=r===0?'draw':r>0?pk:activeGame.peer;if(r>0)activeGame.scores.me++;else if(r<0)activeGame.scores.them++}
function renderRPS(){let h=head('✊✋✌️ Piedra, papel o tijera');if(activeGame.over)h+=`<div class="rps-reveal"><span>${rIcon(activeGame.myChoice)}</span><span>VS</span><span>${rIcon(activeGame.theirChoice)}</span></div>`;else h+=`<div class="rps"><button data-r="rock" class="${activeGame.myChoice==='rock'?'sel':''}" ${activeGame.myChoice?'disabled':''}>✊</button><button data-r="paper" class="${activeGame.myChoice==='paper'?'sel':''}" ${activeGame.myChoice?'disabled':''}>✋</button><button data-r="scissors" class="${activeGame.myChoice==='scissors'?'sel':''}" ${activeGame.myChoice?'disabled':''}>✌️</button></div>`;h+='<div class="game-actions">'+(activeGame.over?'<button class="game-action" id="rematch">Otra ronda</button>':'')+'<button class="game-action ghost" id="quit">Salir</button></div>';$('gameCard').innerHTML=h;common();document.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>chooseRps(b.dataset.r))}
async function chooseRps(choice){if(activeGame.myChoice||activeGame.over)return;activeGame.myChoice=choice;renderRPS();await gameSend(activeGame.peer,{action:'rps',game:'rps',match:activeGame.match,round:activeGame.round,choice});finishRps();renderRPS()}
function resetGame(round){let g=activeGame,s=g.scores,n=emptyGame(g.type,g.peer,g.match,g.host);n.scores=s;n.round=round;activeGame=n}async function rematch(){let r=activeGame.round+1;resetGame(r);renderGame();await gameSend(activeGame.peer,{action:'reset',game:activeGame.type,match:activeGame.match,round:r})}
loadLib();
})();